package com.deange.nastychristmas.ui.resources

val StringResources.Companion.EN
  get() = StringResources(
    add = "Add",
    appName = "Nasty Christmas",
    back = "Back",
    confirm = "Confirm",
    confirmResetApp = "Confirm Reset App",
    editGiftNames = "Edit Gift Names",
    enforceOwnershipDescription = "Require that you cannot steal a gift you have already had in the same round.",
    enforceOwnershipTitle = "Enforce Ownership",
    giftHint = "Gift Name",
    letsGetNasty = "Let’s Get Nasty!",
    newGame = "New Game",
    ok = "OK",
    openGiftDescription = "This finishes the current round.",
    openGiftRoundTitle = "Round %d: %s is opening…",
    openGiftTitle = "Open New Gift",
    playerHint = "Player Name",
    remove = "Remove",
    resetApp = "Reset App",
    round = "Round %d",
    roundTitle = "Going next for Round %d is…",
    settings = "Settings",
    stealFrom = "Steal from %s",
    stealRoundTitle = "%s is going to…",
    thanksForPlaying = "Thanks for playing!",
    undo = "Undo",
  )
